<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 C:\Users\Utente\Desktop\Trasferimento-PC\Projects\Youtube\Threlte\spaceship-header\static\models\spaceship.glb --root /models/ --printwidth 120 --precision 2
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rusty-spaceship-orange-18541ebed6ce44a9923f9b8dc30d87f5
Title: Rusty Spaceship - Orange
-->

<script>
	import {
		AddEquation,
		BoxGeometry,
		CustomBlending,
		CylinderGeometry,
		Group,
		LessEqualDepth,
		MeshBasicMaterial,
		OneFactor
	} from 'three';
	import { T, forwardEventHandlers, useFrame } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { useTexture } from '@threlte/extras';

	export const ref = new Group();
	let afterBurnerScaleY = 1;
	let time = 0;

	const gltf = useGltf('/models/spaceship.glb');
	const map = useTexture('textures/energy-beam-opacity.png');

	gltf.then((model) => {
		function alphaFix(material) {
			material.transparent = true;
			material.alphaToCoverage = true;
			material.depthFunc = LessEqualDepth;
			material.depthTest = true;
			material.depthWrite = true;
		}
		alphaFix(model.materials.spaceship_racer);
		alphaFix(model.materials.cockpit);
		console.log(map);
	});

	const manipulateRocketEngineBloom = (gltf) => {
		gltf.materials.spaceship_racer.emissive.b = 268.1;
		return gltf.materials.spaceship_racer;
	};

	//<T.CylinderGeometry args={[70, 0, 1600, 15]} />
	//const cylinderGeo = new CylinderGeometry(70, 0, 1600, 15);
	//window.cg = cylinderGeo;

	useFrame((_, delta) => {
		time += delta;
		//if (cylinderGeo) {
		const scale = Math.sin(time * 10) * 0.1;
		afterBurnerScaleY = 1 + scale;
		//}
	});

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group scale={0.003} rotation={[0, -Math.PI * 0.5, 0]} position={[0.95, 0, -2.235]}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[739.26, -64.81, 64.77]}
			/>
			<!-- rocket engine -->
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cylinder002_spaceship_racer_0.geometry}
				material={manipulateRocketEngineBloom(gltf)}
				position={[739.69, -59.39, -553.38]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cylinder003_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[742.15, -64.53, -508.88]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube003_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[737.62, 46.84, -176.41]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cylinder004_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[789.52, 59.45, -224.91]}
				rotation={[1, 0, 0]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RExtr001_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[745.54, 159.32, -5.92]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RPanel003_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[739.26, 0, 0]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RPanel003_RExtr_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[739.26, 0, 0]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube002_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[736.79, -267.14, -33.21]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RPanel001_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[739.26, 0, 0]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RPanel003_RExtr001_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[739.26, 0, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube005_cockpit_0.geometry}
				material={gltf.materials.cockpit}
				position={[739.45, 110.44, 307.18]}
				rotation={[0.09, 0, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Sphere_cockpit_0.geometry}
				material={gltf.materials.cockpit}
				position={[739.37, 145.69, 315.6]}
				rotation={[0.17, 0, 0]}
			/>

			{#await map then mapValue}
				<T.Mesh
					position={[740, -60, -1350 - 10]}
					rotation.x={Math.PI * 0.5}
					scale.y={afterBurnerScaleY}
				>
					<T.CylinderGeometry args={[70, 0, 1600, 15]} />
					<T.MeshBasicMaterial
						color={[1.0, 0.4, 0.02]}
						alphaMap={mapValue}
						transparent
						blending={CustomBlending}
						blendDst={OneFactor}
						blendEquation={AddEquation}
					/>
				</T.Mesh>
			{/await}
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
