<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 C:\Users\Utente\Desktop\Trasferimento-PC\Projects\Youtube\Threlte\spaceship-header\static\models\spaceship.glb --root /models/ --printwidth 120 --precision 2
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rusty-spaceship-orange-18541ebed6ce44a9923f9b8dc30d87f5
Title: Rusty Spaceship - Orange
-->

<script>
	import {
		AddEquation,
		BoxGeometry,
		CustomBlending,
		CylinderGeometry,
		Group,
		LessEqualDepth,
		MeshBasicMaterial,
		OneFactor,
		TextureLoader,
		RepeatWrapping
	} from 'three';
	//import { HeatDistortionMaterial } from '../../materials/HeatDistortionMaterial';
	import { T, forwardEventHandlers, useFrame, useTask } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { useTexture } from '@threlte/extras';
	import { r } from '../../helpers';

	export const ref = new Group();
	let afterBurnerScaleY = 1;
	let time = 0;
	// 	const tex=new TextureLoader().load('./textures/grid.png');
	// console.log(tex);

	const gltf = useGltf('./models/spaceship.glb');
	const map = useTexture('textures/energy-beam-opacity.png');

	gltf.then((model) => {
		function alphaFix(material) {
			material.transparent = true;
			material.alphaToCoverage = true;
			material.depthFunc = LessEqualDepth;
			material.depthTest = true;
			material.depthWrite = true;
		}
		alphaFix(model.materials.spaceship_racer);
		alphaFix(model.materials.cockpit);
		console.log(map);
	});

	const manipulateRocketEngineBloom = (gltf) => {
		gltf.materials.spaceship_racer.emissive.b = 268.1;
		return gltf.materials.spaceship_racer;
	};

	//<T.CylinderGeometry args={[70, 0, 1600, 15]} />
	//const cylinderGeo = new CylinderGeometry(70, 0, 1600, 15);
	//window.cg = cylinderGeo;

	let randomValue = 1;
	let targetRandomValue = 1;
	const timeBetweenRandomValuesS = 1; // seconds
	let timeToNextRandomValue = timeBetweenRandomValuesS;
	let lerpSpeed = 0.05; // Adjust this value to change the speed of interpolation
	useTask((delta) => {
		time += delta;
		timeToNextRandomValue -= delta;
		if (timeToNextRandomValue <= 0) {
			targetRandomValue = r(1, 1.5);
			timeToNextRandomValue = timeBetweenRandomValuesS;
		}
		//uniforms.time.value = time;
		// Interpolate towards the target value
		randomValue += (targetRandomValue - randomValue) * lerpSpeed;
		const scale = Math.sin(time * 10 * randomValue) * 0.1;
		afterBurnerScaleY = 1 + scale;
	});

	const component = forwardEventHandlers();
	// const uniforms = {
	// 	time: { value: 0.0 },
	// 	noiseTexture: { value: new TextureLoader().load('./textures/noise.png') },
	// 	distortionStrength: { value: 0.1 }
	// };
	// /Users/thomasranker/code/shader-hmr/src/things/Cactus.js
	const vertexShader = `
		uniform float time;
        varying vec2 vUv;
        void main() {
            vUv = uv;
			float zeroToOne = sin(time)*0.5+0.5;
			// Calculate a wobble effect based on time and the vertex position
        float wobbleAmount = sin(position.y * 10.0 + time) * 1.1;

        // Apply the wobble effect to the vertex position
        vec3 newPosition = position;
        //newPosition.y += wobbleAmount;
		// left right
		//newPosition.x*= 0.5+zeroToOne*0.5;
		// length
		//newPosition.y*=0.5+zeroToOne*0.5;
		// height
		//newPosition.z*=0.5+zeroToOne;

        // Set the final vertex position
        gl_Position = projectionMatrix * modelViewMatrix * vec4(newPosition, 1.0);
            //gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1. );
        }
    `;
	// simple enough? https://www.shadertoy.com/view/XsVSRd
	const fragmentShader = /* glsl */ `
        uniform float time;
        uniform sampler2D noiseTexture;
        uniform float distortionStrength;
        varying vec2 vUv;

		float rand(vec2 n) { return fract(sin(dot(n, vec2(12.9898, 4.1414))) * 43758.5453);}
		float noise(vec2 n) {
		const vec2 d = vec2(0.0, 1.0);
		vec2 b = floor(n), f = smoothstep(vec2(0.0), vec2(1.0), fract(n));
		return mix(mix(rand(b), rand(b + d.yx), f.x), mix(rand(b + d.xy), rand(b + d.yy), f.x), f.y);
		}

        void main() {
            vec2 uv = vUv;

			float textureMoveSpeed = .5;
            // Sample the noise texture
            vec2 noiseUv = uv + vec2(time * textureMoveSpeed, time * textureMoveSpeed);
            vec4 noise = texture2D(noiseTexture, noiseUv);

            // Apply distortion based on noise
            uv += (noise.xy * 2.0 - 1.0) * distortionStrength;

            // Output the distorted color (example: a simple orange color)
            vec4 color = vec4(1.0, 0.4, 0.02, noise.r*pow(uv.y,4.0));

            gl_FragColor = color;
			
        }
    `;

	let texture = new TextureLoader().load('./textures/organic4.jpg');
	texture.wrapS = RepeatWrapping;
	texture.wrapT = RepeatWrapping;
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group scale={0.003} rotation={[0, -Math.PI * 0.5, 0]} position={[0.95, 0, -2.235]}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[739.26, -64.81, 64.77]}
			/>
			<!-- rocket engine -->
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cylinder002_spaceship_racer_0.geometry}
				material={manipulateRocketEngineBloom(gltf)}
				position={[739.69, -59.39, -553.38]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cylinder003_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[742.15, -64.53, -508.88]}
				rotation={[Math.PI / 2, 0, 0]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube003_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[737.62, 46.84, -176.41]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cylinder004_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[789.52, 59.45, -224.91]}
				rotation={[1, 0, 0]}
			/>

			<!-- next 3: outer plates on one side -->
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RExtr001_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[745.54, 159.32, -5.92]}
			/>

			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RPanel003_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[739.26, 0, 0]}
			/>

			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RPanel003_RExtr_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[739.26, 0, 0]}
			/>

			<!-- dunno the next two-->
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube002_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[736.79, -267.14, -33.21]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RPanel001_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[739.26, 0, 0]}
			/>

			<!-- inner stuff -->
			<T.Mesh
				castShadow={false}
				receiveShadow={false}
				geometry={gltf.nodes.Cube001_RPanel003_RExtr001_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
				position={[739.26, 0, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cube005_cockpit_0.geometry}
				material={gltf.materials.cockpit}
				position={[739.45, 110.44, 307.18]}
				rotation={[0.09, 0, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.Sphere_cockpit_0.geometry}
				material={gltf.materials.cockpit}
				position={[739.37, 145.69, 315.6]}
				rotation={[0.17, 0, 0]}
			/>

			{#await map then mapValue}
				<T.Mesh position={[740, -60, -1350 - 10]} rotation.x={Math.PI * 0.5}>
					<T.CylinderGeometry args={[70, 0, 1600, 15]} />
					<T.ShaderMaterial
						{fragmentShader}
						{vertexShader}
						transparent={true}
						uniforms={{
							time: { value: 0.0 },
							noiseTexture: { value: texture },
							distortionStrength: { value: .1 }
						}}
						uniforms.time.value={time}
					/>
				</T.Mesh>
			{/await}
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>

<!--

<T.MeshBasicMaterial
						color={[1.0, 0.4, 0.02]}
						alphaMap={mapValue}
						transparent
						blending={CustomBlending}
						blendDst={OneFactor}
						blendEquation={AddEquation}
					/>

-->
